name: Auto-Bump Components' Versions

on:
  schedule:
    - cron:  '0 5 * * *'

jobs:

  build:
    name: CNAO Component Bump Job
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run bumper script
      run: make ARGS="-config-path=components.yaml -token=${{ secrets.GITHUB_TOKEN }}" auto-bumper
